# Generated by Django 5.2.15 on 2026-07-03 04:50

from django.db import migrations, models


def rename_kaprodi_role_to_ketua_jurusan(apps, schema_editor):
    """Kaprodi role was renamed to Ketua Jurusan — update any rows seeded
    under the old value so existing local/dev databases aren't left with
    users whose role no longer matches any UserRole choice."""
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(role='kaprodi').update(role='ketua_jurusan')


def rename_ketua_jurusan_role_to_kaprodi(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(role='ketua_jurusan').update(role='kaprodi')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Mahasiswa'), ('lecturer', 'Dosen'), ('admin', 'Admin'), ('ketua_jurusan', 'Ketua Jurusan')], default='student', max_length=20),
        ),
        migrations.RunPython(
            rename_kaprodi_role_to_ketua_jurusan,
            reverse_code=rename_ketua_jurusan_role_to_kaprodi,
        ),
    ]
