# Generated by Django 5.2.15 on 2026-07-05 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bimbingan', '0005_session_summary_session_summary_approved_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionLogbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('transcribing', 'Transkripsi'), ('summarizing', 'Merangkum'), ('ready_for_review', 'Menunggu Tinjauan'), ('approved', 'Disetujui'), ('failed', 'Gagal')], default='pending', max_length=20)),
                ('transcript', models.TextField(blank=True, default='')),
                ('summary_raw', models.JSONField(blank=True, default=dict)),
                ('summary_edited', models.JSONField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, default='', max_length=128)),
                ('source_mode', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=10)),
                ('is_manual', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('llm_input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('llm_output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('llm_cost_estimate_idr', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_logbooks', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logbook', to='bimbingan.session')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
