# Generated by Django 5.2.15 on 2026-07-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionlogbook',
            name='campus_entry_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='sessionlogbook',
            name='campus_sync_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionlogbook',
            name='campus_sync_status',
            field=models.CharField(choices=[('not_synced', 'Belum Disinkron'), ('synced', 'Tersinkron'), ('failed', 'Gagal'), ('pending_retry', 'Menunggu Coba Ulang')], default='not_synced', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionlogbook',
            name='campus_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
