# Generated by Django 5.2.15 on 2026-07-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0002_sessionlogbook_campus_entry_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLogbookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('provider', models.CharField(default='sekawan', max_length=20)),
                ('base_url', models.CharField(blank=True, default='', max_length=300)),
                ('token_enc', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konfigurasi Logbook Kampus',
            },
        ),
    ]
