# Generated by Django 5.2.15 on 2026-07-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan', '0004_session_result_notes_session_ts2_sessionrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecording',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
