# Generated by Django 5.2.15 on 2026-07-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan', '0004_session_result_notes_session_ts2_sessionrecording'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='session',
            name='summary_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
