# Generated by Django 5.2.15 on 2026-07-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan', '0006_backfill_summary_to_logbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='session',
            name='summary_approved_at',
        ),
    ]
