# Generated by Django 5.2.15 on 2026-07-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan', '0007_remove_session_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecording',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
