# Generated by Django 5.2.15 on 2026-07-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimbingan', '0008_sessionrecording_duration_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='completion_note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
